"use client";

import {
  Check,
  CheckSquare2,
  FileText,
  Film,
  Grid2X2,
  ImagePlus,
  List,
  Loader2,
  Minus,
  Play,
  RotateCcw,
  Search,
  Square,
  Trash2,
  UploadCloud,
  X,
} from "lucide-react";
import Image from "next/image";
import * as React from "react";
import type { IconType } from "react-icons/lib";
import { Button } from "@/components/ui/button";
import {
  Dialog,
  DialogContent,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from "@/components/ui/dialog";
import { Skeleton } from "@/components/ui/skeleton";
import {
  Select,
  SelectContent,
  SelectItem,
  SelectTrigger,
  SelectValue,
} from "@/components/ui/select";
import { cn } from "@/lib/utils";

export interface ImageVariants {
  thumb: string;
  medium: string;
  full: string;
  raw: string;
}

export interface ImageFormat {
  url: string;
  name?: string;
  type?: string;
  fileName?: string;
  key?: string;
  lastModified?: Date;
  size?: number;
  thumbnail?: string;
  used?: boolean;
  usageCount?: number;
  /**
   * Cloudflare /cdn-cgi/image/ variant URLs generated by the backend.
   * Use these instead of `url` for display — they are device-appropriate
   * and served in the best format (WebP/AVIF) for the requesting browser.
   *
   * - thumb  → 150px, for thumbnails & library grid
   * - medium → 600px, for panels & modals
   * - full   → 1200px, for hero / lightbox
   * - raw    → original CDN URL, no transformation
   */
  variants?: ImageVariants;
  usagePoints?: {
    category?: number;
    productFeatured?: number;
    productGallery?: number;
  };
}

interface ImageModalProps {
  onInsert?: (url: ImageFormat[]) => void;
  selected?: ImageFormat[];
  aspectRatio?: "square" | "portrait" | "landscape" | "free";
  /** Max file size in MB. If omitted, no client-side size limit is enforced. */
  maxSize?: number;
  multiple?: boolean;
  open?: boolean;
  setOpen?: (value: boolean) => void;
  trigger?: boolean;
  className?: string;
  selectedImages?: ImageFormat[];
  icon?: IconType;
  size?: string;
  folder?: string;
  apiUrl?: string;
  apiKey?: string;
  clientCode?: string;
}

// ─── Helpers ────────────────────────────────────────────────────────────────

const formatBytes = (bytes: number | undefined, decimals = 1) => {
  if (!bytes || !+bytes) return "0 B";
  const k = 1024;
  const dm = decimals < 0 ? 0 : decimals;
  const sizes = ["B", "KB", "MB", "GB", "TB"];
  const i = Math.floor(Math.log(bytes) / Math.log(k));
  return `${parseFloat((bytes / k ** i).toFixed(dm))} ${sizes[i]}`;
};

const getDisplayName = (src: ImageFormat) => {
  let name = src.fileName || "";
  if (!name && src.url) {
    name = decodeURIComponent(src.url.split("/").pop() || "");
  }
  if (!name) return "";
  // Strip trailing timestamp appended by storage (e.g. somefile_1712046892123.jpg)
  name = name.replace(/[_-]\d{13,}(\.[^.]+)?$/, (_, p1) => p1 || "");
  const dotIdx = name.lastIndexOf(".");
  const nameWithoutExt = dotIdx > 0 ? name.slice(0, dotIdx) : name;
  const ext = dotIdx > 0 ? name.slice(dotIdx + 1) : "";
  const cleanName = nameWithoutExt.replace(/[-_]/g, " ").trim();
  return ext ? `${cleanName}.${ext}` : cleanName;
};

/**
 * Checks whether a backend media item is an image.
 * Checks categorical type first (backend now returns "image" | "video" | "audio" | "document"),
 * then falls back to MIME type and URL extension for legacy items.
 */
const isImage = (src: ImageFormat) => {
  if (src.type === "image") return true; // backend categorical type
  if (src.type?.startsWith("image/")) return true; // legacy MIME type
  if (src.url?.match(/\.(jpe?g|png|gif|webp|avif|svg)$/i)) return true;
  if (src.fileName?.match(/\.(jpe?g|png|gif|webp|avif|svg)$/i)) return true;
  return false;
};

const isPdf = (src: ImageFormat) => {
  if (src.type === "document") return true; // categorical — all docs treated as pdf filter
  if (src.type === "application/pdf") return true; // legacy MIME type
  if (src.url?.match(/\.pdf$/i)) return true;
  if (src.fileName?.match(/\.pdf$/i)) return true;
  return false;
};

const isVideo = (src: ImageFormat) => {
  if (src.type === "video") return true; // backend categorical type
  if (src.type?.startsWith("video/")) return true; // legacy MIME type
  if (src.url?.match(/\.(mp4|webm|ogg|mov)$/i)) return true;
  if (src.fileName?.match(/\.(mp4|webm|ogg|mov)$/i)) return true;
  return false;
};

const isAudio = (src: ImageFormat) => {
  if (src.type === "audio") return true;
  if (src.type?.startsWith("audio/")) return true;
  if (src.url?.match(/\.(mp3|ogg|wav|aac|flac|m4a|opus)$/i)) return true;
  if (src.fileName?.match(/\.(mp3|ogg|wav|aac|flac|m4a|opus)$/i)) return true;
  return false;
};

// ─── Skeleton Cards ──────────────────────────────────────────────────────────

const GridSkeleton = () => (
  <div className="rounded-lg overflow-hidden border border-border/50 animate-pulse">
    <Skeleton className="aspect-square bg-muted" />
    <div className="px-2 py-1.5 bg-muted/40">
      <Skeleton className="h-2 w-3/4 rounded bg-muted-foreground/20" />
    </div>
  </div>
);

const ListSkeleton = () => (
  <div className="flex items-center gap-3 p-2 rounded-lg border border-border/50 animate-pulse">
    <Skeleton className="h-12 w-12 rounded-md bg-muted shrink-0" />
    <div className="flex-1 space-y-1.5">
      <Skeleton className="h-2.5 w-2/3 rounded bg-muted-foreground/20" />
      <Skeleton className="h-2 w-1/3 rounded bg-muted-foreground/10" />
    </div>
  </div>
);

// ─── Media Thumbnail ─────────────────────────────────────────────────────────

const MediaThumb = ({
  src,
  index,
  mode,
}: {
  src: ImageFormat;
  index: number;
  mode: "grid" | "list";
}) => {
  const cls =
    mode === "grid"
      ? "aspect-square w-full"
      : "h-12 w-12 shrink-0 rounded-md overflow-hidden";

  if (isPdf(src)) {
    return (
      <div
        className={cn(
          "relative flex items-center justify-center bg-red-50 dark:bg-red-950/30",
          cls,
          mode === "grid" && "rounded-none",
        )}
      >
        <FileText className="h-7 w-7 text-red-400" />
        <span className="absolute bottom-1.5 right-1.5 rounded bg-red-500 px-1 py-0.5 text-[8px] font-bold uppercase tracking-widest text-white shadow">
          PDF
        </span>
      </div>
    );
  }

  if (isVideo(src)) {
    return (
      <div
        className={cn(
          "relative overflow-hidden bg-black",
          cls,
          mode === "grid" && "rounded-none",
        )}
      >
        <video
          src={src.url}
          className="h-full w-full object-contain opacity-80"
          muted
          onMouseOver={(e) => e.currentTarget.play()}
          onMouseOut={(e) => {
            e.currentTarget.pause();
            e.currentTarget.currentTime = 0;
          }}
        />
        <div className="absolute inset-0 flex items-center justify-center">
          <div className="rounded-full bg-black/50 p-1.5 backdrop-blur-sm">
            <Play className="h-3 w-3 fill-white text-white" />
          </div>
        </div>
        <span className="absolute bottom-1 left-1 flex items-center gap-0.5 rounded bg-black/60 px-1 py-0.5 backdrop-blur-sm">
          <Film className="h-2.5 w-2.5 text-white" />
          <span className="text-[8px] font-bold uppercase text-white">VID</span>
        </span>
      </div>
    );
  }

  return (
    <div
      className={cn(
        "relative overflow-hidden bg-muted",
        cls,
        mode === "grid" && "rounded-none",
      )}
    >
      <Image
        width={mode === "grid" ? 400 : 48}
        height={mode === "grid" ? 400 : 48}
        loading="lazy"
        src={
          mode === "grid"
            ? (src.variants?.medium ??
              src.variants?.thumb ??
              src.url ??
              "/placeholder.png")
            : (src.variants?.thumb ?? src.url ?? "/placeholder.png")
        }
        alt={src.name || `Media ${index}`}
        sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 33vw"
        className="h-full w-full object-cover transition-transform duration-200 group-hover:scale-[1.04]"
      />
    </div>
  );
};

// ─── Main Component ───────────────────────────────────────────────────────────

export const ImageModal: React.FC<ImageModalProps> = ({
  onInsert,
  selected,
  maxSize,
  multiple = false,
  open,
  setOpen,
  trigger = false,
  className,
  selectedImages: externalSelectedImages,
  icon: Icon = ImagePlus,
  size = "size-10",
  folder = "profile",
  apiUrl,
  apiKey,
  clientCode,
}) => {
  const [isUploading, setIsUploading] = React.useState(false);
  const [uploadStatus, setUploadStatus] = React.useState<
    "idle" | "uploading" | "success" | "error"
  >("idle");
  const [uploadingCount, setUploadingCount] = React.useState(0);
  const [deletingKeys, setDeletingKeys] = React.useState<string[]>([]);
  const [images, setImages] = React.useState<ImageFormat[]>([]);
  const [loadingImages, setLoadingImages] = React.useState(true);
  const [uploadProgress, setUploadProgress] = React.useState(0);
  const [searchQuery, setSearchQuery] = React.useState("");
  const [viewMode, setViewMode] = React.useState<"grid" | "list">("grid");
  const [dragActive, setDragActive] = React.useState(false);
  const [filterType, setFilterType] = React.useState<
    "all" | "image" | "video" | "pdf"
  >("all");
  const [selectedImages, setSelectedImage] = React.useState<ImageFormat[]>();
  const [isOverQuota, setIsOverQuota] = React.useState(false);

  // New state for minimize feature
  const [isMinimized, setIsMinimized] = React.useState(false);
  const [internalOpen, setInternalOpen] = React.useState(false);

  const isOpen = open !== undefined ? open : internalOpen;

  const handleSetOpen = React.useCallback(
    (value: boolean) => {
      if (setOpen) setOpen(value);
      setInternalOpen(value);
      if (!value) setIsMinimized(false);
    },
    [setOpen],
  );

  // Sync external selection and reset state on close
  React.useEffect(() => {
    if (isOpen) {
      setSelectedImage(selected ? [...selected] : []);
    } else {
      setSelectedImage([]);
      setSearchQuery("");
      setFilterType("all");
      setIsMinimized(false);
    }
  }, [selected, isOpen]);

  React.useEffect(() => {
    if (isOpen && externalSelectedImages) {
      setSelectedImage([...externalSelectedImages]);
    }
  }, [externalSelectedImages, isOpen]);

  // Fetch library
  const fetchImages = React.useCallback(async () => {
    try {
      setLoadingImages(true);
      const res = await fetch(
        `${apiUrl}/api/saas/images?q=${encodeURIComponent(searchQuery)}&folder=${folder}`,
        {
          headers: {
            "x-api-key": apiKey!,
            "x-client-code": clientCode!,
          },
        },
      );
      if (!res.ok) throw new Error("Failed to fetch images");
      const json = await res.json();
      setImages(json.data.images ?? []);
      setIsOverQuota(!!json.data.isOverQuota);
    } catch (err: unknown) {
      alert((err as Error).message);
    } finally {
      setLoadingImages(false);
    }
  }, [searchQuery, folder, apiKey, apiUrl, clientCode]);

  React.useEffect(() => {
    fetchImages();
  }, [fetchImages]);

  // Combined filtering (Client-side Search & Types)
  const filteredImages = React.useMemo(() => {
    return images.filter((img) => {
      // Name Search
      if (searchQuery) {
        const displayName = getDisplayName(img).toLowerCase();
        if (!displayName.includes(searchQuery.toLowerCase())) return false;
      }

      // Type Filter
      if (filterType === "all") return true;
      if (filterType === "image") return isImage(img);
      if (filterType === "video") return isVideo(img);
      if (filterType === "pdf") return isPdf(img);
      return true;
    });
  }, [images, filterType, searchQuery]);

  // Select all toggle
  const handleSelectAll = () => {
    if ((selectedImages?.length ?? 0) >= images.length && images.length > 0) {
      setSelectedImage([]);
    } else {
      setSelectedImage([...images]);
    }
  };

  // Upload
  const handleUpload = async (e: React.ChangeEvent<HTMLInputElement>) => {
    const files = Array.from(e.target.files || []);
    if (files.length === 0 || isOverQuota) return;

    const validFiles = files.filter((file) => {
      if (maxSize && file.size > maxSize * 1024 * 1024) {
        alert(`${file.name} exceeds the ${maxSize}MB limit.`);
        return false;
      }
      const ok = ["image/", "video/", "application/pdf"].some((t) =>
        file.type.startsWith(t),
      );
      if (!ok) {
        alert(`${file.name}: unsupported format.`);
        return false;
      }
      return true;
    });

    if (validFiles.length === 0) return;

    setUploadingCount(validFiles.length);
    setIsUploading(true);
    setUploadStatus("uploading");
    setUploadProgress(10);

    try {
      const formData = new FormData();
      validFiles.forEach((file) => formData.append("file", file));
      formData.append("folder", folder);

      const res = await fetch(`${apiUrl}/api/saas/images`, {
        method: "POST",
        body: formData,
        headers: {
          "x-api-key": apiKey!,
          "x-client-code": clientCode!,
        },
      });

      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.error || "Upload failed");
      }

      setUploadProgress(100);
      setUploadStatus("success");
      const json = await res.json();
      const newlyUploaded: ImageFormat[] = Array.isArray(json.data)
        ? json.data
        : [json.data];

      setImages((prev) => [...newlyUploaded, ...prev]);

      if (multiple) {
        setSelectedImage((prev) => [...(prev || []), ...newlyUploaded]);
      } else {
        setSelectedImage([newlyUploaded[0]]);
      }
    } catch (err: unknown) {
      setUploadStatus("error");
      alert((err as Error).message);
    } finally {
      setIsUploading(false);
      setUploadingCount(0);
      setUploadProgress(0);
      // reset file input
      e.target.value = "";
      setTimeout(() => setUploadStatus("idle"), 3000);
    }
  };

  // Drag & drop
  const handleDrag = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    if (e.type === "dragenter" || e.type === "dragover") setDragActive(true);
    if (e.type === "dragleave") setDragActive(false);
  };

  const handleDrop = (e: React.DragEvent) => {
    e.preventDefault();
    e.stopPropagation();
    setDragActive(false);
    const files = e.dataTransfer.files;
    if (files?.[0]) {
      handleUpload({
        target: { files },
      } as React.ChangeEvent<HTMLInputElement>);
    }
  };

  // Selection
  const handleSelectImage = (image: ImageFormat) => {
    if (multiple) {
      setSelectedImage((prev) =>
        prev?.some((item) => item.url === image.url)
          ? prev.filter((item) => item.url !== image.url)
          : [...(prev || []), image],
      );
    } else {
      setSelectedImage([image]);
    }
  };

  const isSelected = (src: ImageFormat) =>
    !!selectedImages?.find((i) => i?.url === src?.url);

  // Delete
  const handleDeleteMedia = async (e: React.MouseEvent, src: ImageFormat) => {
    e.stopPropagation();
    if (!src.key) return alert("Cannot delete: missing media key.");
    if (!confirm("Permanently delete this file?")) return;

    try {
      setDeletingKeys((prev) => [...prev, src.key!]);
      const res = await fetch(
        `${apiUrl}/api/saas/images?key=${encodeURIComponent(src.key)}`,
        {
          method: "DELETE",
          headers: {
            "x-api-key": apiKey!,
            "x-client-code": clientCode!,
          },
        },
      );
      if (!res.ok) {
        const err = await res.json().catch(() => ({}));
        throw new Error(err.error || "Delete failed");
      }
      setImages((prev) => prev.filter((img) => img.key !== src.key));
      setSelectedImage((prev) => prev?.filter((img) => img.key !== src.key));
    } catch (err: unknown) {
      alert((err as Error).message);
    } finally {
      setDeletingKeys((prev) => prev.filter((key) => key !== src.key));
    }
  };

  const selCount = selectedImages?.length ?? 0;
  const allSelected = images.length > 0 && selCount === images.length;

  return (
    <>
      <Dialog open={isOpen && !isMinimized} onOpenChange={handleSetOpen}>
        {trigger && (
          <DialogTrigger asChild>
            <Button
              role="button"
              variant="image-outline"
              size="sm"
              aria-label="Upload Image"
              className={cn(
                "h-inherit flex h-full w-full cursor-pointer items-center justify-center border border-dashed focus-visible:ring-0",
                className,
              )}
            >
              <Icon className={cn(size, "text-primary/70")} />
            </Button>
          </DialogTrigger>
        )}

        <DialogContent className="flex max-h-[88vh] flex-col gap-0 overflow-hidden rounded-xl p-0 shadow-2xl sm:max-w-[760px] bg-[#0A0A10] border-white/10 border">
          {/* ── Header ── */}
          <DialogHeader className="border-b border-white/10 bg-[#0A0A10] px-5 pt-4 pb-3 shrink-0">
            <div className="flex items-center justify-between">
              <DialogTitle className="text-base font-black tracking-tighter text-white">
                Media Library
              </DialogTitle>
              <div className="flex items-center gap-1.5">
                {/* Select All (multi mode only) */}
                {multiple && images.length > 0 && (
                  <button
                    onClick={handleSelectAll}
                    className="flex items-center gap-1.5 rounded-md border border-white/10 px-2.5 py-1 text-[11px] font-bold uppercase tracking-widest text-[#64647A] transition-colors hover:bg-white/5 hover:text-white"
                  >
                    {allSelected ? (
                      <CheckSquare2 className="h-3.5 w-3.5 text-[#22D3EE]" />
                    ) : (
                      <Square className="h-3.5 w-3.5" />
                    )}
                    {allSelected ? "Deselect All" : "Select All"}
                  </button>
                )}

                {/* Refresh */}
                <button
                  onClick={fetchImages}
                  disabled={loadingImages}
                  className="flex h-8 w-8 items-center justify-center rounded-md border border-white/10 text-[#64647A] transition-colors hover:bg-white/5 hover:text-white disabled:opacity-50"
                  title="Refresh"
                >
                  {loadingImages ? (
                    <Loader2 className="h-4 w-4 animate-spin" />
                  ) : (
                    <RotateCcw className="h-4 w-4" />
                  )}
                </button>

                {/* View toggle & Minimize */}
                <div className="flex items-center rounded-md h-8 border border-white/10 bg-[#060608] p-0.5 mr-5">
                  <button
                    onClick={(e) => {
                      e.preventDefault();
                      setIsMinimized(true);
                    }}
                    className="rounded px-2 py-1.5 text-[#64647A] hover:text-white transition-colors"
                    title="Minimize"
                  >
                    <Minus className="h-3.5 w-3.5" />
                  </button>
                  <div className="w-px h-4 bg-white/10 mx-1" />
                  <button
                    onClick={() => setViewMode("grid")}
                    className={cn(
                      "rounded px-2 py-1.5 transition-colors",
                      viewMode === "grid"
                        ? "bg-[#1A1A24] text-white shadow-sm"
                        : "text-[#64647A] hover:text-white",
                    )}
                    title="Grid view"
                  >
                    <Grid2X2 className="h-3.5 w-3.5" />
                  </button>
                  <button
                    onClick={() => setViewMode("list")}
                    className={cn(
                      "rounded px-2 py-1.5 transition-colors",
                      viewMode === "list"
                        ? "bg-[#1A1A24] text-white shadow-sm"
                        : "text-[#64647A] hover:text-white",
                    )}
                    title="List view"
                  >
                    <List className="h-3.5 w-3.5" />
                  </button>
                </div>
              </div>
            </div>

            {/* Search & Filters */}
            <div className="mt-1 flex items-center gap-2">
              <div className="relative flex-1">
                <Search className="pointer-events-none absolute top-1/2 left-2.5 h-3.5 w-3.5 -translate-y-1/2 text-[#64647A]" />
                <input
                  type="search"
                  placeholder="Search files…"
                  value={searchQuery}
                  onChange={(e) => setSearchQuery(e.target.value)}
                  className="h-8 w-full rounded-md border border-white/10 bg-[#060608] pl-8 pr-3 text-sm text-white placeholder:text-[#64647A] focus:border-[#7C6EFA] focus:outline-none focus:ring-1 focus:ring-[#7C6EFA]/30"
                />
              </div>

              <Select
                value={filterType}
                onValueChange={(val: "all" | "image" | "video" | "pdf") =>
                  setFilterType(val)
                }
              >
                <SelectTrigger
                  size="sm"
                  className="w-auto text-[11px] font-medium transition-colors hover:bg-muted/60"
                >
                  <SelectValue placeholder="Format" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all" className="text-xs">
                    All Formats
                  </SelectItem>
                  <SelectItem value="image" className="text-xs">
                    Images
                  </SelectItem>
                  <SelectItem value="video" className="text-xs">
                    Videos
                  </SelectItem>
                  <SelectItem value="pdf" className="text-xs">
                    PDFs
                  </SelectItem>
                </SelectContent>
              </Select>
            </div>
          </DialogHeader>

          {/* ── Scrollable Body ── */}
          <div className="flex-1 overflow-y-auto bg-[#060608] p-4 space-y-4 scrollbar-thin scrollbar-thumb-white/10 scrollbar-track-transparent">
            {/* Upload Zone */}
            <div
              role="button"
              onDragEnter={handleDrag}
              onDragLeave={handleDrag}
              onDragOver={handleDrag}
              onDrop={handleDrop}
              className={cn(
                "relative flex items-center gap-4 rounded-xl border-2 border-dashed px-5 py-4 transition-all duration-200",
                dragActive
                  ? "border-[#7C6EFA] bg-[#7C6EFA]/5 scale-[1.01]"
                  : "border-white/10 bg-[#0A0A10] hover:border-[#7C6EFA]/50 hover:bg-[#7C6EFA]/5",
                (isUploading || isOverQuota) &&
                  "pointer-events-none opacity-90",
              )}
            >
              {isOverQuota ? (
                <div className="flex w-full items-center gap-4 py-2 opacity-80">
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-destructive/10 border border-destructive/20 text-destructive">
                    <RotateCcw className="h-5 w-5" />
                  </div>
                  <div>
                    <p className="text-sm font-semibold text-destructive">
                      Storage Limit Reached
                    </p>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      Clear some space or upgrade your plan to upload more files
                    </p>
                  </div>
                </div>
              ) : isUploading ? (
                <div className="flex w-full items-center gap-4">
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary/10">
                    <Loader2 className="h-5 w-5 animate-spin text-primary" />
                  </div>
                  <div className="flex-1 min-w-0">
                    <p className="text-sm font-medium">
                      Uploading {uploadingCount} file
                      {uploadingCount > 1 ? "s" : ""}…
                    </p>
                    <div className="mt-1.5 h-1.5 w-full overflow-hidden rounded-full bg-muted">
                      <div
                        className="h-full rounded-full bg-primary transition-all duration-300"
                        style={{ width: `${uploadProgress || 30}%` }}
                      />
                    </div>
                  </div>
                  <span className="text-xs tabular-nums text-muted-foreground">
                    {uploadProgress}%
                  </span>
                </div>
              ) : (
                <>
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-full bg-primary/8 border border-primary/20">
                    <UploadCloud className="h-5 w-5 text-primary" />
                  </div>
                  <div className="min-w-0">
                    <p className="text-sm font-medium leading-snug">
                      Drop files or{" "}
                      <span className="text-primary underline decoration-dotted underline-offset-2 cursor-pointer">
                        browse
                      </span>
                    </p>
                    <p className="text-xs text-muted-foreground mt-0.5">
                      Images, Videos, PDFs
                      {maxSize ? ` — up to ${maxSize} MB each` : ""}
                    </p>
                  </div>
                  <input
                    type="file"
                    accept="image/*,video/*,application/pdf"
                    multiple
                    onChange={handleUpload}
                    className="absolute inset-0 cursor-pointer opacity-0"
                  />
                </>
              )}
            </div>

            {/* Gallery Header */}
            <div className="flex items-center justify-between border-b border-white/10 pb-2">
              <span className="text-[11px] font-bold uppercase tracking-widest text-[#64647A]">
                Media Library
                {!loadingImages && images.length > 0 && (
                  <span className="ml-2 rounded-full bg-[#1A1A24] px-2 py-0.5 text-[9px] font-bold text-[#64647A]">
                    {images.length}
                  </span>
                )}
              </span>
            </div>

            {/* Gallery */}
            {loadingImages ? (
              <div
                className={cn(
                  viewMode === "grid"
                    ? "grid grid-cols-3 sm:grid-cols-4 gap-2"
                    : "space-y-1.5",
                )}
              >
                {[...Array(viewMode === "grid" ? 10 : 5)].map((_, i) =>
                  viewMode === "grid" ? (
                    <GridSkeleton key={i} />
                  ) : (
                    <ListSkeleton key={i} />
                  ),
                )}
              </div>
            ) : filteredImages.length === 0 ? (
              <div className="flex flex-col items-center justify-center py-20 text-center">
                <div className="mb-4 flex h-16 w-16 items-center justify-center rounded-full bg-[#1A1A24] border border-white/10">
                  <Search className="h-7 w-7 text-[#64647A]" />
                </div>
                <p className="text-sm font-semibold text-white">
                  {searchQuery || filterType !== "all"
                    ? "No matching files"
                    : "Your library is empty"}
                </p>
                <p className="mt-1.5 text-xs text-[#64647A] max-w-[200px]">
                  {searchQuery || filterType !== "all"
                    ? "Try adjusting your search or filters to find what you're looking for."
                    : "Upload your first file to see it here in the library."}
                </p>
                {(searchQuery || filterType !== "all") && (
                  <Button
                    variant="link"
                    size="sm"
                    className="mt-2 text-[#22D3EE]"
                    onClick={() => {
                      setSearchQuery("");
                      setFilterType("all");
                    }}
                  >
                    Reset all filters
                  </Button>
                )}
              </div>
            ) : (
              <div
                className={cn(
                  viewMode === "grid"
                    ? "grid grid-cols-3 sm:grid-cols-4 gap-2"
                    : "space-y-1.5",
                )}
              >
                {/* Upload skeleton placeholders */}
                {isUploading &&
                  [...Array(uploadingCount)].map((_, i) =>
                    viewMode === "grid" ? (
                      <GridSkeleton key={`up-${i}`} />
                    ) : (
                      <ListSkeleton key={`up-${i}`} />
                    ),
                  )}

                {filteredImages.map((src, i) => {
                  const isDeleting = src.key && deletingKeys.includes(src.key);
                  const selected = isSelected(src);
                  const displayName = getDisplayName(src);

                  if (isDeleting) {
                    return viewMode === "grid" ? (
                      <GridSkeleton key={src.key || i} />
                    ) : (
                      <ListSkeleton key={src.key || i} />
                    );
                  }

                  if (viewMode === "list") {
                    return (
                      <div
                        key={src.key || i}
                        onClick={() => handleSelectImage(src)}
                        className={cn(
                          "group flex cursor-pointer items-center gap-3 rounded-lg border p-2 transition-all duration-150",
                          selected
                            ? "border-[#7C6EFA] bg-[#7C6EFA]/5 ring-1 ring-[#7C6EFA]/30"
                            : "border-white/10 bg-[#0A0A10] hover:border-white/20 hover:bg-[#1A1A24]",
                        )}
                      >
                        {/* Thumb */}
                        <MediaThumb src={src} index={i} mode="list" />

                        {/* Info */}
                        <div className="min-w-0 flex-1">
                          <p
                            className="text-xs font-medium leading-snug text-white"
                            style={{ wordBreak: "break-word" }}
                            title={displayName}
                          >
                            {displayName || `Media ${i + 1}`}
                          </p>
                          <p className="mt-0.5 text-[10px] text-[#64647A]">
                            {src.size ? formatBytes(src.size) : "—"}
                            {src.lastModified &&
                              ` · ${new Date(src.lastModified).toLocaleDateString()}`}
                          </p>
                        </div>

                        {/* Actions */}
                        <div className="flex shrink-0 items-center gap-1.5 pr-1">
                          <button
                            onClick={(e) => handleDeleteMedia(e, src)}
                            className="rounded-md p-1 text-[#64647A] opacity-0 transition-all hover:bg-destructive/10 hover:text-destructive group-hover:opacity-100"
                            title="Delete"
                          >
                            <Trash2 className="h-3.5 w-3.5" />
                          </button>
                          <div
                            className={cn(
                              "flex h-5 w-5 items-center justify-center rounded-full border-2 transition-all",
                              selected
                                ? "border-[#7C6EFA] bg-[#7C6EFA] text-black"
                                : "border-white/10 bg-[#060608] group-hover:border-[#7C6EFA]/50",
                            )}
                          >
                            {selected && <Check className="h-3 w-3" />}
                          </div>
                        </div>
                      </div>
                    );
                  }

                  // Grid view
                  return (
                    <div
                      key={src.key || i}
                      onClick={() => handleSelectImage(src)}
                      className={cn(
                        "group relative cursor-pointer overflow-hidden rounded-lg border transition-all duration-150",
                        selected
                          ? "border-[#7C6EFA] ring-2 ring-[#7C6EFA]/40 ring-offset-1"
                          : "border-white/10 hover:border-[#7C6EFA]/40",
                      )}
                    >
                      {/* Thumbnail */}
                      <MediaThumb src={src} index={i} mode="grid" />

                      {/* Hover overlay */}
                      <div
                        className={cn(
                          "absolute inset-0 bg-black/0 transition-colors duration-150 group-hover:bg-black/10",
                          selected && "bg-primary/10",
                        )}
                      />

                      {/* Delete button */}
                      <button
                        onClick={(e) => handleDeleteMedia(e, src)}
                        className="absolute top-1.5 left-1.5 z-10 flex h-6 w-6 items-center justify-center rounded-full bg-black/60 text-white opacity-0 shadow backdrop-blur-sm transition-all hover:bg-red-500 group-hover:opacity-100"
                        title="Delete"
                      >
                        <Trash2 className="h-3 w-3" />
                      </button>

                      {/* Selection badge */}
                      <div
                        className={cn(
                          "absolute top-1.5 right-1.5 z-10 flex h-5 w-5 items-center justify-center rounded-full border-2 transition-all",
                          selected
                            ? "border-[#7C6EFA] bg-[#7C6EFA] text-black shadow"
                            : "border-white/70 bg-black/30 backdrop-blur-sm opacity-0 group-hover:opacity-100",
                        )}
                      >
                        {selected && <Check className="h-3 w-3" />}
                      </div>

                      {/* Filename label */}
                      <div className="border-t border-white/10 bg-[#0A0A10]/95 px-2 py-1">
                        <p
                          className="text-[9px] font-medium text-[#64647A]"
                          style={{ wordBreak: "break-word", lineHeight: "1.2" }}
                          title={displayName}
                        >
                          {displayName || `Media ${i + 1}`}
                        </p>
                      </div>
                    </div>
                  );
                })}
              </div>
            )}
          </div>

          {/* ── Footer ── */}
          <div className="shrink-0 border-t border-white/10 bg-[#0A0A10] px-5 py-3">
            <div className="flex items-center justify-between gap-3">
              {/* Selection status */}
              <div className="flex items-center gap-3">
                <span className="text-xs text-[#64647A]">
                  {selCount > 0 ? (
                    <span className="flex items-center gap-1.5 font-medium text-white">
                      <div className="flex h-4 w-4 items-center justify-center rounded-full bg-[#22D3EE] text-black">
                        <Check className="h-2.5 w-2.5" />
                      </div>
                      {selCount} selected
                    </span>
                  ) : (
                    "No files selected"
                  )}
                </span>
                {selCount > 0 && (
                  <Button
                    variant="ghost"
                    size="sm"
                    onClick={() => setSelectedImage([])}
                    className="h-6 px-2 text-xs text-[#64647A] hover:text-white"
                  >
                    Clear
                  </Button>
                )}
              </div>

              <div className="flex items-center gap-2">
                <Button
                  variant="outline"
                  size="sm"
                  className="h-8 px-4 text-xs border-white/10 bg-[#060608] hover:bg-white/5 text-white"
                  onClick={() => {
                    setOpen?.(!open);
                    setSelectedImage([]);
                  }}
                >
                  Cancel
                </Button>
                <Button
                  size="sm"
                  disabled={!selCount || isUploading}
                  onClick={() => {
                    onInsert?.(selectedImages!);
                    setOpen?.(!open);
                    setSelectedImage([]);
                  }}
                  className="bg-linear-to-r from-[#7C6EFA] to-[#22D3EE] hover:shadow-[0_0_20px_rgba(124,110,250,0.35)] text-black font-bold h-8 gap-1.5 px-5 text-xs rounded-xl border-none"
                >
                  {isUploading ? (
                    <>
                      <Loader2 className="h-3.5 w-3.5 animate-spin" />
                      Uploading…
                    </>
                  ) : (
                    <>
                      <Check className="h-3.5 w-3.5" />
                      {selCount > 0
                        ? `Use ${selCount} file${selCount > 1 ? "s" : ""}`
                        : "Select"}
                    </>
                  )}
                </Button>
              </div>
            </div>
          </div>
        </DialogContent>
      </Dialog>

      {isOpen && isMinimized && (
        <div
          className="fixed bottom-6 right-6 z-[100] flex cursor-pointer items-center gap-3 overflow-hidden rounded-full border border-border bg-background p-2 pr-4 shadow-2xl transition-all hover:scale-105 animate-in slide-in-from-bottom-5 fade-in duration-300"
          onClick={() => setIsMinimized(false)}
        >
          {uploadStatus === "uploading" ? (
            <>
              <div className="relative flex h-10 w-10 items-center justify-center rounded-full bg-primary/10">
                <svg
                  className="absolute inset-0 h-full w-full -rotate-90"
                  viewBox="0 0 36 36"
                >
                  <path
                    className="text-primary/20"
                    d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                  />
                  <path
                    className="text-primary transition-all duration-300"
                    strokeDasharray={`${uploadProgress}, 100`}
                    d="M18 2.0845 a 15.9155 15.9155 0 0 1 0 31.831 a 15.9155 15.9155 0 0 1 0 -31.831"
                    fill="none"
                    stroke="currentColor"
                    strokeWidth="2"
                  />
                </svg>
                <UploadCloud className="h-4 w-4 text-primary animate-pulse" />
              </div>
              <div className="flex flex-col">
                <span className="text-sm font-semibold text-foreground">
                  Uploading...
                </span>
                <span className="text-[10px] text-muted-foreground">
                  {uploadProgress}% - {uploadingCount} file
                  {uploadingCount > 1 ? "s" : ""}
                </span>
              </div>
            </>
          ) : uploadStatus === "success" ? (
            <>
              <div className="flex h-10 w-10 items-center justify-center rounded-full bg-green-500/10 text-green-500">
                <Check className="h-5 w-5" />
              </div>
              <div className="flex flex-col">
                <span className="text-sm font-semibold text-foreground">
                  Upload Complete
                </span>
              </div>
            </>
          ) : uploadStatus === "error" ? (
            <>
              <div className="flex h-10 w-10 items-center justify-center rounded-full bg-destructive/10 text-destructive">
                <X className="h-5 w-5" />
              </div>
              <div className="flex flex-col">
                <span className="text-sm font-semibold text-foreground">
                  Upload Failed
                </span>
              </div>
            </>
          ) : (
            <>
              <div className="flex h-10 w-10 items-center justify-center rounded-full bg-primary/10">
                <ImagePlus className="h-5 w-5 text-primary" />
              </div>
              <div className="flex flex-col">
                <span className="text-sm font-semibold text-foreground">
                  Media Library
                </span>
                <span className="text-[10px] text-muted-foreground">
                  Click to restore
                </span>
              </div>
            </>
          )}
        </div>
      )}
    </>
  );
};
